version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - data-volume:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd/.htpasswd:/etc/nginx/.htpasswd


  php:
    image: meda10/bp_tor_php:with_files
    container_name: php_container
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    expose:
      - 9000
    networks:
      - app-network
    volumes:
      - data-volume:/var/www/html/Tor-simulations/www/html

volumes:
     data-volume:

networks:
  app-network:
    driver: bridge

